### ISSUE TITLE
Clicking upgrades and keypress issue

### ISSUE THREAD

**Issue by BailyKushab** [TylerPottsDev/the-startup-game#2]
To reproduce, start the game and start typing. Then click one of the upgrades. Without clicking anywhere else, return to typing. You will see the alert that you have insufficient funds. Somehow typing is triggering the click event. 

Changing buyUpgrade to the code below will prevent the commit from firing and let you see that a MouseEvent is being triggered. 

```
buyUpgrade(event, index) {
      console.log(event);
      if (event.screenX > 0) {
        this.$store.commit("buyUpgrade", {
          index,
          amount: 1
        });
      }
    }
```

**Comment by TylerPottsDev** [comment]
Hi @BailyKushab do you think you'd have time to make another pull request for this? You done a great job with the last. :)

**Comment by BailyKushab** [comment]
Thanks! I can make one later tonight.
